name: Test WireGuard Installation

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.repository == 'taimurey/wireguard-install'
    strategy:
      matrix:
        container:
          - "ubuntu:22.04"
          - "debian:11"
          - "debian:12"
          - "fedora:39"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            apt-transport-https \
            ca-certificates \
            curl \
            gnupg-agent \
            software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
          sudo systemctl start docker

      - name: Setup Docker in Docker
        run: |
          sudo mkdir -p /etc/docker
          echo '{
            "experimental": true,
            "features": {
              "buildkit": true
            },
            "storage-driver": "overlay2"
          }' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: Test WireGuard Installation (Debian/Ubuntu)
        if: contains(matrix.container, 'ubuntu') || contains(matrix.container, 'debian')
        run: |
          # Create a Docker network for DinD
          docker network create wireguard-test

          # Start DinD container
          docker run -d --privileged --name dind \
            --network wireguard-test \
            -v ${{ github.workspace }}:/workspace \
            docker:dind

          # Wait for Docker to be ready in DinD
          sleep 10

          # Run test in the container
          docker exec dind sh -c '
            apk add --no-cache bash curl
            cd /workspace
            chmod +x wireguard-manager.sh
            ./wireguard-manager.sh auto_install=true'

      - name: Test WireGuard Installation (Fedora)
        if: contains(matrix.container, 'fedora')
        run: |
          # Create a Docker network for DinD
          docker network create wireguard-test

          # Start DinD container
          docker run -d --privileged --name dind \
            --network wireguard-test \
            -v ${{ github.workspace }}:/workspace \
            docker:dind

          # Wait for Docker to be ready in DinD
          sleep 10

          # Run test in the container
          docker exec dind sh -c '
            apk add --no-cache bash curl
            cd /workspace
            chmod +x wireguard-manager.sh
            ./wireguard-manager.sh auto_install=true'

      - name: Verify WireGuard Status
        run: |
          docker exec dind sh -c '
            if docker ps | grep -q wireguard; then
              echo "WireGuard is running"
              exit 0
            else
              echo "WireGuard is not running"
              exit 1
            fi'

      - name: Cleanup
        if: always()
        run: |
          docker stop dind || true
          docker rm dind || true
          docker network rm wireguard-test || true
          docker system prune -af
