name: Test WireGuard Installation

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.repository == 'taimurey/wireguard-install'
    strategy:
      matrix:
        container:
          - "ubuntu:22.04"
          - "ubuntu:24.04"
          - "debian:11"
          - "debian:12"
          - "fedora:39"
          - "fedora:40"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          docker --version

      - name: Test WireGuard Installation (Debian/Ubuntu)
        if: contains(matrix.container, 'ubuntu') || contains(matrix.container, 'debian')
        run: |
          docker run --privileged -v ${{ github.workspace }}:/workspace ${{ matrix.container }} /bin/bash -c '
            apt-get update
            apt-get install -y curl sudo systemd systemd-sysv git
            cd /workspace
            chmod +x wireguard-manager.sh
            echo "testadmin" > /tmp/answers
            echo "testpass" >> /tmp/answers
            echo "testpass" >> /tmp/answers
            echo "2" >> /tmp/answers
            cat /tmp/answers | ./wireguard-manager.sh
            if docker ps | grep -q wireguard; then
              echo "Success: WireGuard is running"
              exit 0
            else
              echo "Failure: WireGuard is not running"
              exit 1
            fi'

      - name: Test WireGuard Installation (Fedora)
        if: contains(matrix.container, 'fedora')
        run: |
          docker run --privileged -v ${{ github.workspace }}:/workspace ${{ matrix.container }} /bin/bash -c '
            dnf install -y curl sudo systemd systemd-sysv git
            cd /workspace
            chmod +x wireguard-manager.sh
            echo "testadmin" > /tmp/answers
            echo "testpass" >> /tmp/answers
            echo "testpass" >> /tmp/answers
            echo "2" >> /tmp/answers
            cat /tmp/answers | ./wireguard-manager.sh
            if docker ps | grep -q wireguard; then
              echo "Success: WireGuard is running"
              exit 0
            else
              echo "Failure: WireGuard is not running"
              exit 1
            fi'

      - name: Cleanup
        if: always()
        run: |
          docker system prune -af
